# Generated by Django 2.2.4 on 2019-08-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_indicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Caminho', models.CharField(max_length=199, unique=True, verbose_name='Caminho')),
            ],
            options={
                'db_table': 'MENU_INDICADORES',
            },
        ),
    ]
