# Generated by Django 2.2.4 on 2019-08-31 06:28

import contas.models.usuario
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_requisitorusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'supervisor',
                'verbose_name_plural': 'supervisores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='TesterUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'tester',
                'verbose_name_plural': 'testers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
    ]
