# Generated by Django 2.2.4 on 2019-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cadastro_lote',
            constraint=models.UniqueConstraint(fields=('Lote_numero',), name='Constraint_lote'),
        ),
    ]
