# Generated by Django 2.2.4 on 2019-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0002_cadastro_placas_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_lote',
            name='Ativo',
            field=models.BooleanField(default=True, verbose_name='Lote Ativo'),
        ),
        migrations.AddField(
            model_name='cadastro_lote',
            name='Qtd_placa',
            field=models.IntegerField(default=1, verbose_name='Quantidade de placa'),
        ),
    ]
