# Generated by Django 2.2.4 on 2019-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0003_auto_20190926_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_placas',
            name='Ativo',
            field=models.BooleanField(default=True, verbose_name='Modelo Ativo'),
        ),
    ]
